### ISSUE TITLE
Not really an issue.

### ISSUE THREAD

**Issue by NotMercvry** [Devorkk/CreyGaMaTheme#1]
Hi! I know this is not really an issue, but I'm not active on discord - and I don't want to bother much.
However, I do have an question. Is it alright ( Do you mind ) If I use this font & scrollbar import for my own theme creation that I'm working on? I might also include it in an previous release (FrostedSpace). 

Since it's your creation, I'm asking to not "skid" without any knowledge - and of course, you will be partially credited.

**Comment by Devorkk** [comment]
Hey, of course you can use it, if you need anything else contact me. 🙂
